### ISSUE TITLE
VS2019 compatibilty

### ISSUE THREAD

**Issue by ilCosmico** [hamidshahid/shelvesetcomparer#6]
Any chance to update the project to make it compatible with Visual Studio 2019 too?

**Comment by BrianS36** [comment]
This would be very handy

**Comment by ilCosmico** [comment]
I tried it, but I get the below error trying to install .vsix 

![image](https://user-images.githubusercontent.com/8678145/102067865-fd425300-3dfb-11eb-8696-f235e25b0b85.png)

Any chance to publish it to the [Visual Studio Marketplace](https://marketplace.visualstudio.com/), please? :)

**Comment by icnocop** [comment]
@ilCosmico that error during installation is fixed in https://github.com/hamidshahid/shelvesetcomparer/pull/10

**Comment by ilCosmico** [comment]
Thanks a lot @icnocop!

Visual Studio 2019 16.8.4 gives the below alert but it seems to work anyway... I don't know if you want/can fix it too :)
![image](https://user-images.githubusercontent.com/8678145/106120207-61c03400-6156-11eb-92c1-83af1087214f.png)

**Comment by icnocop** [comment]
Hi @ilCosmico.

I'm glad it's working for you now as well.

That warning appears because the [`ProvideAutoLoad` attribute](https://github.com/hamidshahid/shelvesetcomparer/blob/8f5d47c817f3d13f52d17c50a16b88e33e71d93f/ShelvesetComparer/ShelvesetComparerPackage.cs#L33) is deprecated.

The `ProvideAutoLoad` attribute is required for the [`Initialize` method](https://github.com/hamidshahid/shelvesetcomparer/blob/8f5d47c817f3d13f52d17c50a16b88e33e71d93f/ShelvesetComparer/ShelvesetComparerPackage.cs#L58) to be called.

[`ShelvesetComparerPackage` inherits from the `Package` base class](https://github.com/hamidshahid/shelvesetcomparer/blob/8f5d47c817f3d13f52d17c50a16b88e33e71d93f/ShelvesetComparer/ShelvesetComparerPackage.cs#L34) and should be migrated to use the `AsyncPackage` base class instead to resolve this issue. 

I recommend at least creating a new/separate issue so it can be tracked better as this issue is closed.

I don't think I'll be personally working to fix that issue though because the extension is working for me regardless of the warning, I haven't personally noticed that much degradation in performance, and the warning message can be dismissed.

For more information, see https://github.com/microsoft/VSSDK-Extensibility-Samples/tree/master/AsyncPackageMigration.

Thank you. 🙂

**Comment by ilCosmico** [comment]
Hi @icnocop,

Thanks for the hint, I will open a separate issue for this :)
